### ISSUE TITLE
Missing mboehme/corebench folders

### ISSUE THREAD

**Issue by daparpon** [mboehme/corebench#1]
Hi! I am interested in downloading the source code of the CoreBench benchmarks and patches, in order to evaluate my experimental tool on them. However, although I followed the instructions in the README file of the distribution, I cannot get the Docker image running. More specifically, when I clone the repository and try to execute the "docker pull mboehme/corebench" command, I get the following message:

"Using default tag: latest
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

I then tried to build the image manually, but every time I run the docker build command, I get this other message:

"unable to prepare context: path "mboehme/corebench" not found"

I noticed that there is no "mboehme" folder in the GitHub distribution, and, according to the later message, it may be related to the problem.

I would appreciate any help regarding this problem.

Thanks in advance.

**Comment by mboehme** [comment]
I just tested the setup again and it still works fine. Looking at your error message, it seems your Docker is not running. You need to install and run Docker. You can test this by running  `sudo docker run -it ubuntu /bin/bash`
